[LM-10081] Overflow Menu
LikeMindsCommunity/LikeMinds-Flutter-Chat-UI pull request #24
Opened 2023-11-03 12:18 UTC by AnujLM

## Description

**Features**

**Bugs**

-  Fixed Overflow Popup Menu

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Hotfix (fixes a breaking changes)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2023-11-06 06:13 UTC, TyagiLikeMinds requested changes

2023-11-06 06:13 UTC, TyagiLikeMinds commented on lib/src/models/menu_decoration_model.dart
> +class LMMenuDecoration {
Can we use `PopUpMenuThemeData` class provided by Flutter in itself

2023-11-06 06:13 UTC, TyagiLikeMinds commented on lib/src/widgets/common/menu/menu.dart
> +              elevation: menuDecoration?.elevation,
Can we replace LMMenuDecoration class with PopUpMenuThemeData class provided by Flutter in itself

2023-11-06 06:13 UTC, TyagiLikeMinds commented on lib/src/widgets/conversation/chat_bubble.dart
> +  final LMMenuDecoration? menuDecoration;
`PopUpMenuThemeData` class

2023-11-14 08:52 UTC, divyanshgandhilm approved these changes

2023-11-14 08:52 UTC, divyanshgandhilm commented
Behtereen! Now it looks good.

2023-11-14 09:05 UTC, merged

2023-11-14 10:16 UTC, divyanshgandhilm commented
**CHANGELOG mentions**

Breaking changes in LMChatBubble - removed menu, and menuItems keys. Add deprecated tag in them.
Plus define the new variables - menuBuilder.